### PR TITLE
Add Social media icons

### PR DESCRIPTION
**Pull request by apals**
screen2

### CODE REVIEW

**Comment by Jeppes** [comment]
Should we use last year's icons or will there be new ones this year?

**Comment by apals** [comment]
We only change the color of the logo, the rest is facebook's/twitter's/.. job imo

**Comment by Jeppes** [comment]
ok, shouldn't be hard to swap out anyway

**Comment by kyriaki93** [comment]
The rope is last year's signature... so yes we should swap them asap! 

Which social icons do you need? Facebook, linkedin, twitter and instagram? And i guess in png, or maybe svg?

**Comment by apals** [comment]
svg is fine @kyriaki93. we dont need instagram

**Comment by kyriaki93** [comment]
I have now sent the new logos to you @apals on mail :)

**Comment by apals** [comment]
Cool beans!

**Pull request merged**
